#!/bin/sh
### BEGIN INIT INFO
# Provides:          advantech
# Required-Start:
# Required-Stop:
# Default-Start: S
# Default-Stop: 6
# Short-Description:
# Description:       Linux advinit
### END INIT INFO

case "$1" in
start)
    # Create /etc/serialID
    CPUINFO=`cat /proc/cpuinfo | grep "Serial"`
    echo ${CPUINFO##*:} > /etc/serialID

    # Chmod of /userdata
    if [ -d "/userdata" ];then
        chmod 0777 /userdata 
    fi

    # set default volume
	AUDIO=$(aplay -l | grep rt5660 | cut -c 6)
    amixer -c$AUDIO cset name="Speaker Playback Volume" 30%
	
    # mount userdata and oem
    mount /dev/disk/by-partlabel/userdata /userdata

	#power down-up typec usb
    # echo 0 > /sys/class/gpio/gpio151/value
    # sleep 1
    # echo 1 > /sys/class/gpio/gpio151/value

	#set gpu freq
    echo performance >  /sys/devices/platform/ff9a0000.gpu/devfreq/ff9a0000.gpu/governor
    ;;
stop)
    ;;
restart|reload)
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0

