#!/bin/sh
#
# Note: this is a sample and will not be run as is.
# xrandr -o left
xrandr --output HDMI-1 --rotate left
xrandr --output DSI-1 --rotate left

# show Logo
feh -F /etc/lxdm/logo.png &
sleep 2
ps -ef |grep feh |awk '{print $2}' |xargs kill -9
