#!/bin/sh
### BEGIN INIT INFO
# Provides:          advantech
# Required-Start:
# Required-Stop:
# Default-Start: S
# Default-Stop: 6
# Short-Description:
# Description:       Linux advinit
### END INIT INFO

case "$1" in
start)
    # Create /etc/serialID
    CPUINFO=`cat /proc/cpuinfo | grep "Serial"`
    echo ${CPUINFO##*:} > /etc/serialID

    # Chmod of /userdata
    if [ -d "/userdata" ];then
        chmod 0777 /userdata 
    fi

    # stop hostapd.service
    systemctl stop hostapd.service
    ;;
stop)
    ;;
restart|reload)
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0

